Ft makeupartist
KitechRW/akadomorw pull request #183
Opened 2021-12-06 09:35 UTC by Clarisse-3924

2021-12-07 10:50 UTC, fridolinho requested changes
@Clarisse-3924 can you find a way of display the welcome text and the call to action button "COntact US" before the page is scrolled.

2021-12-10 14:43 UTC, Ramadhan0 commented on Makeupartist/script.js
> +
move this description in the middle

and also this description does not sound right.

2021-12-10 14:57 UTC, Ramadhan0 requested changes

2021-12-10 14:57 UTC, Ramadhan0 commented on ireme/.vscode/settings.json
> +{
remove **`Ireme`** related files

2022-01-14 11:03 UTC, closed without merging