Ft 250jewelries
KitechRW/akadomorw pull request #187
Opened 2021-12-08 13:20 UTC by Clarisse-3924

2021-12-10 15:56 UTC, Ramadhan0 requested changes

2021-12-10 15:56 UTC, Ramadhan0 commented on Benevolencehardware/.vscode/settings.json
> +{
please remove **`benevolence hardware`** files

2021-12-10 15:56 UTC, Ramadhan0 commented on Makeupartist/components/about.html
> +<div class="" id="about">
remove **`makeup artist`** files

2021-12-10 15:56 UTC, Ramadhan0 commented on ireme/.vscode/settings.json
> +{
remove **`ireme`** files

2021-12-10 15:56 UTC, Ramadhan0 commented on styledhomeMart/components/about.html
> +<div class="" id="about">
remove **`style home art`** files

2021-12-20 05:45 UTC, fridolinho commented
1. No meta tags
2. No info@ domain email used in contact details and send_email.php

2021-12-21 14:28 UTC, closed without merging