ft-raystarhome.rw
KitechRW/akadomorw pull request #217
Opened 2022-03-30 10:36 UTC by emmymbaraga

editing template to raystarhome.rw website

2022-03-30 12:02 UTC, fridolinho requested changes
1. rename service menu to what we do and remove collections menu
2. Rename About menu to who we are
3. pull down who we are section and merge it with know more about us section
4. Remove existing what we section.
5. Rename collection section to what we do with just 2 categories(our collections and House for rent)
6. Remove social media icons.

2022-03-31 06:03 UTC, fridolinho commented
![](https://github.trello.services/images/mini-trello-icon.png) [raystarhome.rw](https://trello.com/c/yWQMVOQi/150-raystarhomerw)

2022-04-01 11:43 UTC, Ramadhan0 requested changes
Fix the responsiveness @emmymbaraga

2022-04-01 11:43 UTC, Ramadhan0 commented on raystarhome.rw/components/gallery.html
> +        <div class="items">
###  These buttons are too big for smaller screens.  
![sss](https://user-images.githubusercontent.com/46961521/161256336-8d3254ef-1c78-48a3-966d-8a9df96445c5.png)

- make them responsive and youre good to go.

2022-04-18 08:44 UTC, fridolinho approved these changes

2022-04-18 08:44 UTC, closed without merging