ft-updated template with login
KitechRW/akadomorw pull request #218
Opened 2022-04-04 20:37 UTC by Shimex7

2022-04-05 08:27 UTC, Ramadhan0 requested changes

2022-04-05 08:27 UTC, Ramadhan0 commented on template/components/navbar.html
> +					href="https://mail.kitech.rw/SOGo/"
Hi @Shimex7, This **Link** is supposed to open in a different tab.

2022-04-05 13:07 UTC, fridolinho commented
![](https://github.trello.services/images/mini-trello-icon.png) [add Login menu to akadomorw template](https://trello.com/c/q2v7QQLE/152-add-login-menu-to-akadomorw-template)

2022-04-11 12:35 UTC, Ramadhan0 approved these changes

2022-04-11 12:37 UTC, merged