adding shinecentury website
KitechRW/akadomorw pull request #89
Opened 2021-06-04 12:51 UTC by Clarisse-3924

2021-06-08 05:31 UTC, fridolinho approved these changes

2022-03-31 06:02 UTC, fridolinho commented
![](https://github.trello.services/images/mini-trello-icon.png) [Shinecentury updates](https://trello.com/c/QpCVsQ9n/142-shinecentury-updates)

2022-04-05 09:27 UTC, Ramadhan0 requested changes
@Clarisse-3924, 

-  Remove all Images you are not using. you are only supposed to have like 4 images in this file.
- Remove all empty files

2022-04-05 09:27 UTC, Ramadhan0 commented on template/components/team.html
> +						<div style="text-align: center;">
Hi @Clarisse-3924, please put these in a nicer desiign with nice fonts

- like : this   ![acc](https://user-images.githubusercontent.com/46961521/161722521-ee94a393-22fa-400e-a280-da90cd40682f.png) 
**for the desktop**

and : this   ![acc2](https://user-images.githubusercontent.com/46961521/161722950-d3c8cb0c-6bb1-446a-bc65-a83733628896.png)
**for small screen**

or maybe if you have a better design u can implement it instead of just a text

2022-04-05 09:35 UTC, Clarisse-3924 commented on template/components/team.html
> +						<div style="text-align: center;">
Hi @Ramadhan0 thank you for feedback!
I will work on your feedback and I will let you once is completed

2022-04-14 07:13 UTC, Ramadhan0 approved these changes

2022-04-14 08:40 UTC, Ramadhan0 reviewed
Hi @Clarisse-3924 ,
You have done a good job, however, there is a small change on-page.

- On the big screen:

> The space between those two cards is too big.

> The account number should not touch the `border of the card` add some `padding`

![buttons1](https://user-images.githubusercontent.com/46961521/163345412-035c7b75-bfec-4aa6-8679-a7041fd45034.png)



- On the small screen: 

> There should be space between the cards

> Cards should be in the middle

> and again add `padding` on the account numbers

 
![buttons2](https://user-images.githubusercontent.com/46961521/163346610-1b121d46-3582-43e5-89c5-c34c30efb988.png)


- **you should consider using `Bootstrap`. With Bootstrap,you can easily implement all those feedback above**

2022-04-21 08:08 UTC, closed without merging